### PR TITLE
Clarify installation instructions in WindowsQuickStart.md

### PR DESCRIPTION
**Pull request by kendalharland**

### CODE REVIEW

**Review by compnerd — CHANGES_REQUESTED** [review]
Please send these upstream (compnerd/swift-build).

**Comment by kendalharland** [comment]
> Please send these upstream (compnerd/swift-build).

Sure. I think I need to be granted access

**Comment by compnerd** [comment]
You should be able to fork and create a PR :)

**Comment by kendalharland** [comment]
> You should be able to fork and create a PR :)

Done, although I need perms to add reviewers 😄 https://github.com/compnerd/swift-build/pull/729

**Review by hjyamauchi — APPROVED** [review]

**Pull request closed without merging**
